//! Lead DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Lead;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::LeadSource;
use crate::domain::entity::LeadStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Lead
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateLeadDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "lead_name")]
    pub lead_name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "organization_name")]
    pub organization_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "whatsapp_no")]
    pub whatsapp_no: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    pub source: LeadSource,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "campaign_id")]
    pub campaign_id: Option<Uuid>,
    pub status: LeadStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "converted_at")]
    pub converted_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "owner_user_id")]
    pub owner_user_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sales_team_id")]
    pub sales_team_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "utm_source")]
    pub utm_source: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "utm_medium")]
    pub utm_medium: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "utm_campaign")]
    pub utm_campaign: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "merged_into_lead_id")]
    pub merged_into_lead_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "merged_at")]
    pub merged_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Lead
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateLeadDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "lead_name")]
    pub lead_name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "organization_name")]
    pub organization_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "whatsapp_no")]
    pub whatsapp_no: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    pub source: LeadSource,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "campaign_id")]
    pub campaign_id: Option<Uuid>,
    pub status: LeadStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "converted_at")]
    pub converted_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "owner_user_id")]
    pub owner_user_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sales_team_id")]
    pub sales_team_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "utm_source")]
    pub utm_source: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "utm_medium")]
    pub utm_medium: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "utm_campaign")]
    pub utm_campaign: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "merged_into_lead_id")]
    pub merged_into_lead_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "merged_at")]
    pub merged_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Lead
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchLeadDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "lead_name")]
    pub lead_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "organization_name")]
    pub organization_name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "whatsapp_no")]
    pub whatsapp_no: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<LeadSource>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "campaign_id")]
    pub campaign_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<LeadStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "party_id")]
    pub party_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "converted_at")]
    pub converted_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "owner_user_id")]
    pub owner_user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "sales_team_id")]
    pub sales_team_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "utm_source")]
    pub utm_source: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "utm_medium")]
    pub utm_medium: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "utm_campaign")]
    pub utm_campaign: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "merged_into_lead_id")]
    pub merged_into_lead_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "merged_at")]
    pub merged_at: Option<DateTime<Utc>>,
}

impl PatchLeadDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.lead_name.is_some() || self.organization_name.is_some() || self.phone.is_some() || self.whatsapp_no.is_some() || self.email.is_some() || self.source.is_some() || self.campaign_id.is_some() || self.status.is_some() || self.party_id.is_some() || self.converted_at.is_some() || self.notes.is_some() || self.owner_user_id.is_some() || self.sales_team_id.is_some() || self.utm_source.is_some() || self.utm_medium.is_some() || self.utm_campaign.is_some() || self.merged_into_lead_id.is_some() || self.merged_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Lead entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LeadResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub lead_name: String,
    pub organization_name: Option<String>,
    pub phone: Option<String>,
    pub whatsapp_no: Option<String>,
    pub email: Option<String>,
    pub source: LeadSource,
    pub campaign_id: Option<Uuid>,
    pub status: LeadStatus,
    pub party_id: Option<Uuid>,
    pub converted_at: Option<DateTime<Utc>>,
    pub notes: Option<String>,
    pub owner_user_id: Option<Uuid>,
    pub sales_team_id: Option<Uuid>,
    pub utm_source: Option<String>,
    pub utm_medium: Option<String>,
    pub utm_campaign: Option<String>,
    pub merged_into_lead_id: Option<Uuid>,
    pub merged_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Lead entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LeadListResponseDto {
    /// List of items
    pub items: Vec<LeadResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl LeadListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<LeadResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct LeadSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub lead_name: String,
    pub organization_name: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Lead> for LeadResponseDto {
    fn from(entity: Lead) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            lead_name: entity.lead_name,
            organization_name: entity.organization_name,
            phone: entity.phone,
            whatsapp_no: entity.whatsapp_no,
            email: entity.email,
            source: entity.source,
            campaign_id: entity.campaign_id,
            status: entity.status,
            party_id: entity.party_id,
            converted_at: entity.converted_at,
            notes: entity.notes,
            owner_user_id: entity.owner_user_id,
            sales_team_id: entity.sales_team_id,
            utm_source: entity.utm_source,
            utm_medium: entity.utm_medium,
            utm_campaign: entity.utm_campaign,
            merged_into_lead_id: entity.merged_into_lead_id,
            merged_at: entity.merged_at,
            metadata: entity.metadata,
        }
    }
}

impl From<Lead> for LeadSummaryDto {
    fn from(entity: Lead) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            lead_name: entity.lead_name,
            organization_name: entity.organization_name,
            created_at,
        }
    }
}

impl From<CreateLeadDto> for Lead {
    fn from(dto: CreateLeadDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            lead_name: dto.lead_name,
            organization_name: dto.organization_name,
            phone: dto.phone,
            whatsapp_no: dto.whatsapp_no,
            email: dto.email,
            source: dto.source,
            campaign_id: dto.campaign_id,
            status: dto.status,
            party_id: dto.party_id,
            converted_at: dto.converted_at,
            notes: dto.notes,
            owner_user_id: dto.owner_user_id,
            sales_team_id: dto.sales_team_id,
            utm_source: dto.utm_source,
            utm_medium: dto.utm_medium,
            utm_campaign: dto.utm_campaign,
            merged_into_lead_id: dto.merged_into_lead_id,
            merged_at: dto.merged_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Lead> for LeadResponseDto {
    fn from(entity: &Lead) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            lead_name: entity.lead_name.clone(),
            organization_name: entity.organization_name.clone(),
            phone: entity.phone.clone(),
            whatsapp_no: entity.whatsapp_no.clone(),
            email: entity.email.clone(),
            source: entity.source.clone(),
            campaign_id: entity.campaign_id.clone(),
            status: entity.status.clone(),
            party_id: entity.party_id.clone(),
            converted_at: entity.converted_at.clone(),
            notes: entity.notes.clone(),
            owner_user_id: entity.owner_user_id.clone(),
            sales_team_id: entity.sales_team_id.clone(),
            utm_source: entity.utm_source.clone(),
            utm_medium: entity.utm_medium.clone(),
            utm_campaign: entity.utm_campaign.clone(),
            merged_into_lead_id: entity.merged_into_lead_id.clone(),
            merged_at: entity.merged_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateLeadDto> for Lead {
    fn from_create_dto(dto: CreateLeadDto) -> backbone_core::ServiceResult<Self> {
        Ok(Lead::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateLeadDto> for Lead {
    fn apply_update(mut self, dto: UpdateLeadDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.lead_name = dto.lead_name;
        self.organization_name = dto.organization_name;
        self.phone = dto.phone;
        self.whatsapp_no = dto.whatsapp_no;
        self.email = dto.email;
        self.source = dto.source;
        self.campaign_id = dto.campaign_id;
        self.status = dto.status;
        self.party_id = dto.party_id;
        self.converted_at = dto.converted_at;
        self.notes = dto.notes;
        self.owner_user_id = dto.owner_user_id;
        self.sales_team_id = dto.sales_team_id;
        self.utm_source = dto.utm_source;
        self.utm_medium = dto.utm_medium;
        self.utm_campaign = dto.utm_campaign;
        self.merged_into_lead_id = dto.merged_into_lead_id;
        self.merged_at = dto.merged_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Lead here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
