//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod lead_service;

// <<< CUSTOM
pub mod lead_ports;
pub mod lead_write_service;
// END CUSTOM

pub use lead_service::LeadService;
// <<< CUSTOM
pub use lead_ports::{PartyPort, CustomerFromLead, PartyAck, CrmRejected};
pub use lead_write_service::{LeadWriteService, NewLead, LeadError};
// END CUSTOM