-- Lead Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the lead.leads table.
-- Customize this file to add your initial data.

-- INSERT INTO lead.leads (
--     id,
--     company_id,
--     lead_name,
--     organization_name,
--     phone,
--     whatsapp_no,
--     email,
--     source,
--     campaign_id,
--     status,
--     party_id,
--     converted_at,
--     notes,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO lead.leads (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

