-- Enum types for lead module
-- Generated by metaphor-schema

-- Create lead_source enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'lead_source') THEN
        CREATE TYPE lead_source AS ENUM ('whatsapp', 'instagram', 'referral', 'website', 'walk_in', 'other');
    END IF;
END
$$;

-- Create lead_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'lead_status') THEN
        CREATE TYPE lead_status AS ENUM ('new', 'contacted', 'qualified', 'converted', 'junk', 'lost');
    END IF;
END
$$;

