-- Company RLS fence for lead module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for lead.leads
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE lead.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE lead.leads FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS leads_company_isolation ON lead.leads;
CREATE POLICY leads_company_isolation ON lead.leads
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

