-- Migration: Create leads table
-- Generated by metaphor-schema

-- Create lead_source enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'lead_source') THEN
        CREATE TYPE lead_source AS ENUM ('whatsapp', 'instagram', 'referral', 'website', 'walk_in', 'other');
    END IF;
END
$$;

-- Create lead_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'lead_status') THEN
        CREATE TYPE lead_status AS ENUM ('new', 'contacted', 'qualified', 'converted', 'junk', 'lost');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS lead;

CREATE TABLE IF NOT EXISTS lead.leads (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    lead_name TEXT NOT NULL,
    organization_name TEXT,
    phone TEXT,
    whatsapp_no TEXT,
    email TEXT,
    source lead_source NOT NULL DEFAULT 'whatsapp',
    campaign_id UUID,
    status lead_status NOT NULL DEFAULT 'new',
    party_id UUID,
    converted_at TIMESTAMPTZ,
    notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_leads_company_id_status ON lead.leads (company_id, status);

CREATE INDEX IF NOT EXISTS idx_leads_company_id_whatsapp_no ON lead.leads (company_id, whatsapp_no);

CREATE INDEX IF NOT EXISTS idx_leads_party_id ON lead.leads (party_id);

CREATE INDEX IF NOT EXISTS idx_leads_campaign_id ON lead.leads (campaign_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_leads_metadata_gin ON lead.leads USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_leads_metadata_deleted_at ON lead.leads ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_leads_metadata_created_at ON lead.leads ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_leads_metadata_updated_at ON lead.leads ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION lead.leads_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS leads_insert_audit ON lead.leads;
CREATE TRIGGER leads_insert_audit BEFORE INSERT ON lead.leads
    FOR EACH ROW EXECUTE FUNCTION lead.leads_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS leads_update_audit ON lead.leads;
CREATE TRIGGER leads_update_audit BEFORE UPDATE ON lead.leads
    FOR EACH ROW EXECUTE FUNCTION lead.leads_audit_timestamp();
