//! Domain events for Lead entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Lead;

/// Domain events for Lead — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Lead>)` variant.
pub type LeadEvent = CrudEvent<Lead>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Lead events.
pub type LeadEventPublisher = Arc<dyn CrudEventPublisher<Lead> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopLeadEventPublisher = NoOpCrudEventPublisher<Lead>;
