//! Event handler trait for Lead events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::LeadEvent;

/// Event handler for Lead events.
/// Implement this trait to react to Lead lifecycle events.
pub trait LeadEventHandler: EventHandler<LeadEvent> {}
