//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod lead_events;
pub mod lead_event_handlers;

pub use lead_events::{LeadEvent, LeadEventPublisher, NoopLeadEventPublisher};
pub use lead_event_handlers::LeadEventHandler;

// <<< CUSTOM
pub mod lead_conversion_events;
pub use lead_conversion_events::{
    LeadQualified, LeadConverted, LeadMerged, LeadConversionEvent, LeadEventSink, LoggingLeadSink,
};
// END CUSTOM
