//! Lead seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial Lead data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// LEAD SEEDER
// ============================================================================

/// Seeder for lead
pub struct SeedLeadSeeder;

impl SeedLeadSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedLeadSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedLeadSeeder {
    fn name(&self) -> &'static str {
        "SeedLeadSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if lead.leads table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM lead.leads")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/lead_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM lead.leads")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

