//! Repository trait for Lead aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Lead aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Lead, LeadSource, LeadStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct LeadPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl LeadPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct LeadPaginatedResult {
    pub data: Vec<Lead>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct LeadFilter {
    pub company_id: Option<Uuid>,
    pub lead_name: Option<String>,
    pub organization_name: Option<String>,
    pub phone: Option<String>,
    pub whatsapp_no: Option<String>,
    pub email: Option<String>,
    pub source: Option<LeadSource>,
    pub campaign_id: Option<Uuid>,
    pub status: Option<LeadStatus>,
    pub party_id: Option<Uuid>,
    pub notes: Option<String>,
    pub owner_user_id: Option<Uuid>,
    pub sales_team_id: Option<Uuid>,
    pub merged_into_lead_id: Option<Uuid>,
}

impl LeadFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.lead_name.is_some() || self.organization_name.is_some() || self.phone.is_some() || self.whatsapp_no.is_some() || self.email.is_some() || self.source.is_some() || self.campaign_id.is_some() || self.status.is_some() || self.party_id.is_some() || self.notes.is_some() || self.owner_user_id.is_some() || self.sales_team_id.is_some() || self.merged_into_lead_id.is_some()
    }
}

/// Repository trait for Lead aggregate
///
/// This trait defines the persistence contract for Lead entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait LeadRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new lead entity
    async fn save(&self, entity: &Lead) -> Result<Lead>;

    /// Find lead by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Lead>>;

    /// Find all lead entities
    async fn find_all(&self) -> Result<Vec<Lead>>;

    /// Update lead by ID
    async fn update(&self, id: &str, entity: &Lead) -> Result<Option<Lead>>;

    /// Delete lead by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List lead with pagination
    async fn list(&self, params: LeadPaginationParams) -> Result<LeadPaginatedResult>;

    /// List lead with pagination and filters
    async fn list_with_filters(&self, params: LeadPaginationParams, filters: LeadFilter) -> Result<LeadPaginatedResult>;

    /// Count all lead entities
    async fn count(&self) -> Result<u64>;

    /// Count lead entities matching filters
    async fn count_with_filters(&self, filters: LeadFilter) -> Result<u64>;

    /// Check if lead exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete lead by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted lead by ID
    async fn restore(&self, id: &str) -> Result<Option<Lead>>;

    /// List soft-deleted lead entities
    async fn list_deleted(&self, params: LeadPaginationParams) -> Result<LeadPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save lead entities
    async fn bulk_save(&self, entities: &[Lead]) -> Result<Vec<Lead>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
