//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod lead_repository;

// Re-exports
pub use lead_repository::{
    LeadRepository,
    LeadPaginationParams,
    LeadPaginatedResult,
    LeadFilter,
};
