//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod lead_repository;
mod lead_website_visitor_repository;

// Custom persistence modules
// <<< CUSTOM
pub use lead_repository::{
    DuplicateKeyGroupRow, LeadForConvertRow, LeadForQualifyRow, LeadMatchRow, NewLeadRow,
};
pub use lead_website_visitor_repository::{
    find_capture_match_on_conn, insert_lead_on_conn, leads_for_visitor_on_conn,
    link_website_visitor_on_conn, WebsiteCaptureMatch,
};
// END CUSTOM

// Re-exports
pub use lead_repository::LeadRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
