//! Validator for Lead entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Lead>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Lead;

/// Validator type alias for Lead entities.
pub type LeadValidator = EntityValidator<Lead>;

/// Build a validator for Lead with all schema-defined field rules.
pub fn lead_validator() -> LeadValidator {
    EntityValidator::new()
        .rule(RequiredString::new("lead_name", |e: &Lead| &e.lead_name))
        .rule(OptionalNotBlank::new("organization_name", |e: &Lead| e.organization_name.as_deref()))
        .rule(OptionalNotBlank::new("phone", |e: &Lead| e.phone.as_deref()))
        .rule(OptionalNotBlank::new("whatsapp_no", |e: &Lead| e.whatsapp_no.as_deref()))
        .rule(OptionalNotBlank::new("email", |e: &Lead| e.email.as_deref()))
        .rule(OptionalNotBlank::new("notes", |e: &Lead| e.notes.as_deref()))
        .rule(OptionalNotBlank::new("utm_source", |e: &Lead| e.utm_source.as_deref()))
        .rule(OptionalNotBlank::new("utm_medium", |e: &Lead| e.utm_medium.as_deref()))
        .rule(OptionalNotBlank::new("utm_campaign", |e: &Lead| e.utm_campaign.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
