//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod lead_validator;

pub use lead_validator::{LeadValidator, lead_validator};

// <<< CUSTOM
// END CUSTOM
