//! Lead API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Lead CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// LEAD TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Lead
pub struct LeadTestData;

impl TestDataGenerator for LeadTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "lead_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "organization_name": null,
            "phone": null,
            "whatsapp_no": null,
            "email": null,
            "source": "whatsapp",
            "campaign_id": null,
            "status": "new",
            "party_id": null,
            "converted_at": now,
            "notes": null,
            "owner_user_id": null,
            "sales_team_id": null,
            "utm_source": null,
            "utm_medium": null,
            "utm_campaign": null,
            "merged_into_lead_id": null,
            "merged_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "lead_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "organization_name": null,
            "phone": null,
            "whatsapp_no": null,
            "email": null,
            "source": "whatsapp",
            "campaign_id": null,
            "status": "new",
            "party_id": null,
            "converted_at": now,
            "notes": null,
            "owner_user_id": null,
            "sales_team_id": null,
            "utm_source": null,
            "utm_medium": null,
            "utm_campaign": null,
            "merged_into_lead_id": null,
            "merged_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// LEAD API TEST
// ============================================================================

/// Lead API test suite
pub struct LeadApiTest {
    inner: GenericCrudTest<LeadTestData>,
}

impl LeadApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/leads", "Lead");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, LeadTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for LeadApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_lead_crud() {
        let mut test = LeadApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Lead specific tests here
// <<< CUSTOM TESTS END >>>
