//! Lead Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::LeadService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Lead service
    pub lead_service: Arc<LeadService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        lead_service: Arc<LeadService>
    ) -> Self {
        Self {
            lead_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::LeadModule) -> Self {
        Self {
            lead_service: module.lead_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    lead_service: Option<Arc<LeadService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Lead service.
    pub fn with_lead_service(mut self, service: Arc<LeadService>) -> Self {
        self.lead_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            lead_service: self.lead_service.expect("lead_service is required"),
        }
    }
}
