//! Public events for Lead module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// LEAD EVENTS
// ============================================================================

/// Event published when a Lead is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeadCreatedEvent {
    pub id: LeadId,
    pub data: LeadDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Lead is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeadUpdatedEvent {
    pub id: LeadId,
    pub data: LeadDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Lead is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeadDeletedEvent {
    pub id: LeadId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Lead module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum LeadEvent {
    LeadCreated(LeadCreatedEvent),
    LeadUpdated(LeadUpdatedEvent),
    LeadDeleted(LeadDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeadEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for LeadEventMetadata {
    fn default() -> Self {
        Self {
            module: "lead",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
