//! Lead Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Lead exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use lead::exports::{LeadDto, LeadQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `LeadDto` - Data transfer object for Lead
/// - `LeadSummary` - Summary view of Lead
/// - `LeadId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `LeadQueryService` - Read-only queries
///
/// ## Public Events
/// - `LeadCreatedEvent` - Published when Lead is created
/// - `LeadUpdatedEvent` - Published when Lead is updated
/// - `LeadDeletedEvent` - Published when Lead is deleted
pub struct ExportSummary;
