//! Public services for Lead module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Lead module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait LeadQueryService: Send + Sync {
    /// Get Lead by ID
    async fn get_lead(&self, id: LeadId) -> Result<Option<LeadDto>>;

    /// Get Lead summary by ID
    async fn get_lead_summary(&self, id: LeadId) -> Result<Option<LeadSummary>>;

    /// Check if Lead exists
    async fn lead_exists(&self, id: LeadId) -> Result<bool>;

}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
