//! Public types for Lead module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use crate::domain::entity::*;

// ============================================================================
// LEAD TYPES
// ============================================================================

/// Type-safe ID for Lead
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct LeadId(pub Uuid);

impl LeadId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for LeadId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<LeadId> for Uuid {
    fn from(id: LeadId) -> Self {
        id.0
    }
}

/// Data transfer object for Lead
///
/// This is the public representation of Lead for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeadDto {
    pub id: LeadId,
    pub company_id: Uuid,
    pub lead_name: String,
    pub organization_name: Option<String>,
    pub phone: Option<String>,
    pub whatsapp_no: Option<String>,
    pub email: Option<String>,
    pub source: LeadSource,
    pub campaign_id: Option<Uuid>,
    pub status: LeadStatus,
    pub party_id: Option<Uuid>,
    pub converted_at: Option<DateTime<Utc>>,
    pub notes: Option<String>,
    pub owner_user_id: Option<Uuid>,
    pub sales_team_id: Option<Uuid>,
    pub merged_into_lead_id: Option<Uuid>,
    pub merged_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of Lead for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeadSummary {
    pub id: LeadId,
    pub lead_name: String,
    pub organization_name: Option<String>,
    pub email: Option<String>,
    pub status: LeadStatus,
}

/// Reference to Lead for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LeadRef {
    pub id: LeadId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
