//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod lead_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use lead_handler::{create_lead_routes, create_lead_read_routes, create_lead_write_routes};
// <<< CUSTOM
// END CUSTOM
