//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod lead_handler;

// <<< CUSTOM
pub mod guarded_routes;
// END CUSTOM

// Re-exports
pub use lead_handler::{create_lead_routes, create_lead_read_routes, create_lead_write_routes};
// <<< CUSTOM
pub use guarded_routes::{create_guarded_lead_routes, create_guarded_lead_routes_with_sink};
// END CUSTOM
